// <auto-generated />
using Capitulo06Migrations.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Capitulo06Migrations.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180612201741_AtendimentoCreate")]
    partial class AtendimentoCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("OficinaModels.Atendimentos.Atendimento", b =>
                {
                    b.Property<long?>("AtendimentoID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ClienteID");

                    b.Property<DateTime>("DataHoraChegada");

                    b.Property<DateTime?>("DataHoraEntrega");

                    b.Property<DateTime>("DataHoraPrometida");

                    b.Property<string>("Veiculo");

                    b.HasKey("AtendimentoID");

                    b.HasIndex("ClienteID");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("OficinaModels.Cadastros.Cliente", b =>
                {
                    b.Property<long?>("ClienteID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EMail");

                    b.Property<string>("Nome");

                    b.Property<string>("Telefone");

                    b.HasKey("ClienteID");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("OficinaModels.Cadastros.Servico", b =>
                {
                    b.Property<long?>("ServicoID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<double>("Valor");

                    b.HasKey("ServicoID");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("OficinaModels.Atendimentos.Atendimento", b =>
                {
                    b.HasOne("OficinaModels.Cadastros.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID");
                });
#pragma warning restore 612, 618
        }
    }
}
