#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PesoIdealEIMC.Resource", IsApplication=true)]

namespace PesoIdealEIMC
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000b
			public const int btnCalcular = 2130968587;
			
			// aapt resource value: 0x7f040013
			public const int btnNovoIMC = 2130968595;
			
			// aapt resource value: 0x7f040002
			public const int edtAltura = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int edtPeso = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int linearLayout1 = 2130968576;
			
			// aapt resource value: 0x7f04000e
			public const int linearLayout2 = 2130968590;
			
			// aapt resource value: 0x7f04000a
			public const int linearLayout3 = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int linearLayout4 = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int rdbFeminino = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int rdbMasculino = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int rdgSexo = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int textView1 = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int textView2 = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int textView3 = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int textView5 = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int textView7 = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int textView9 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int txtClassificacao = 2130968594;
			
			// aapt resource value: 0x7f04000d
			public const int txtIMC = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int txtPesoIdeal = 2130968592;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int pgResultado = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
